# Generated by Django 2.2.4 on 2019-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='cancellato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenota',
            name='cancellato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='cancellato',
            field=models.BooleanField(default=False),
        ),
    ]
