# Generated by Django 2.2.4 on 2019-08-13 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190812_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='durata',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
