# Generated by Django 2.2.4 on 2019-08-18 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0002_auto_20190818_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('letto', models.BooleanField(default=False)),
                ('userDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDestinatario', to=settings.AUTH_USER_MODEL)),
                ('userMittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMittente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
