# Generated by Django 2.2.4 on 2019-08-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_messaggio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAttesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Corso')),
            ],
        ),
        migrations.CreateModel(
            name='Inserito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listaAttesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.ListaAttesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
