# Generated by Django 2.2.4 on 2019-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_corso_durata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='durata',
            field=models.FloatField(),
        ),
    ]
