# Generated by Django 2.2.4 on 2019-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20190813_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='posti_prenotati',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
