# Generated by Django 2.2.4 on 2019-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_inserito_listaattesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserito',
            name='cancellato',
            field=models.BooleanField(default=False),
        ),
    ]
