# Generated by Django 2.2.4 on 2019-08-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_corso_posti_prenotati'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenota',
            old_name='corso_id',
            new_name='corso',
        ),
    ]
