# Generated by Django 2.2.4 on 2019-08-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_inserito_cancellato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='num',
        ),
    ]
